# Site
name: 'Mundana'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/blogs'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Obed Junias
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Greetings! I am Obed Junias - the Neural Navigator. Armed with a keyboard and an insatiable thirst for innovation, I embark on thrilling expeditions into the vast realms of Artificial Intelligence and Computer Science. Join me as we navigate the uncharted territories of technology, pushing boundaries, unraveling mysteries, and unleashing the full potential of human ingenuity. Let's soar through the digital skies, where ideas take flight and possibilities are endless. Welcome aboard, fellow adventurers, with the Neural Navigator - to the place where innovation knows no bounds!"
      email:          obed.junias@gmail.com
      twitter:        https://twitter.com/neuralNavigatr

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
